spring:
  datasource:
    name: test
    url: jdbc:mysql://47.113.229.47:3306/test
    username: root
    password: wyj_123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml